=== seventer/iteraplan/WebContent/WEB-INF/classes/LandscapeDiagramXML.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="landscapeDiagramXML" type="landscapeDiagramXML"/>

  <xs:element name="queryFormXML" type="queryForm"/>

  <xs:complexType name="landscapeDiagramXML">
    <xs:sequence>
      <xs:element name="color" type="enumAttribute" minOccurs="0"/>
      <xs:element name="columnAxisScalesWithContent" type="xs:boolean"/>
      <xs:element name="columnQuery" type="queryResultXML" minOccurs="0"/>
      <xs:element name="contentQuery" type="queryResultXML" minOccurs="0"/>
      <xs:element name="filterEmptyColumns" type="xs:boolean" minOccurs="0"/>
      <xs:element name="filterEmptyRows" type="xs:boolean" minOccurs="0"/>
      <xs:element name="lineType" type="enumAttribute" minOccurs="0"/>
      <xs:element name="rowQuery" type="queryResultXML" minOccurs="0"/>
      <xs:element name="selectedColumnAttributeId" type="xs:int" minOccurs="0"/>
      <xs:element name="selectedColumnOption" type="contentOption"/>
      <xs:element name="selectedColumnRelation" type="xs:string" minOccurs="0"/>
      <xs:element name="selectedRowAttributeId" type="xs:int" minOccurs="0"/>
      <xs:element name="selectedGraphicsFormat" type="xs:string" minOccurs="0"/>
      <xs:element name="selectedResultIds" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="id" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="selectedRowOption" type="contentOption"/>
      <xs:element name="selectedRowRelation" type="xs:string" minOccurs="0"/>
      <xs:element name="strictRelations" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="showUnspecifiedRelations" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="scaleDownContentElements" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="globalScalingEnabled" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="spanContentBetweenCells" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="useColorRange" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="useNamesLegend" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="showSavedQueryInfo" type="xs:boolean" minOccurs="0" maxOccurs="1" />
      <xs:element name="sideAxisBottomLevel" type="xs:int"/>
      <xs:element name="sideAxisTopLevel" type="xs:int"/>
      <xs:element name="topAxisBottomLevel" type="xs:int"/>
      <xs:element name="topAxisTopLevel" type="xs:int"/>
      <xs:element name="contentBottomLevel" type="xs:int" minOccurs="0"/>
      <xs:element name="contentTopLevel" type="xs:int" minOccurs="0"/>
      <xs:element name="version" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="contentType" type="landscapeDiagramContentTypeXML" use="required"/>
    <xs:attribute name="dialogStep" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="enumAttribute">
    <xs:sequence>
      <xs:element name="attributeValues" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="selectedStyles" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="style" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="attributeId" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="queryResultXML">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="queryForms" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="queryForm" type="queryForm" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="selectedResultIds" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="id" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
		  <xs:element name="timeseriesQuery" type="timeseriesQuery" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="queryName" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractXMLElement" abstract="true">
    <xs:sequence/>
  </xs:complexType>

	<xs:complexType name="queryForm">
		<xs:sequence>
			<xs:element name="extension" type="presentationExtension"
				minOccurs="0" />
			<xs:element name="postProcessingStrategies" 
			  	minOccurs="0" type="postProcessingStrategies" />
			<!-- Deprecated: To be used for backwards-compatibility only. -->
			<xs:element name="postprocessingStrategy" type="xs:string"
				minOccurs="0" />			
			<xs:element name="queryUserInput" type="queryUserInput"
				minOccurs="0" />
			<xs:element name="secondLevel" type="queryForm" nillable="true"
				minOccurs="0" maxOccurs="unbounded" />	
		</xs:sequence>
		<xs:attribute name="typeXML" type="typeXML" use="required" />
	</xs:complexType>
  
	<xs:complexType name="postProcessingStrategies">
		<xs:sequence>
			<xs:element name="postProcessingStrategy" type="postProcessingStrategy" minOccurs="0"
				maxOccurs="unbounded" />			
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="postProcessingStrategy">	
		<xs:sequence>
			<xs:element name="additionalOptions" type="additionalOptions" minOccurs="0" 
				maxOccurs="unbounded" />
		</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required" />	
	</xs:complexType>

	 <xs:complexType name="additionalOptions">
		<xs:sequence>
			<xs:element name="additionalOption" type="xs:string" minOccurs="0" 
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType> 

  <xs:complexType name="presentationExtension">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="name" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="queryUserInput">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="noAssignements" type="xs:boolean"/>
          <xs:element name="queryFirstLevels" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="queryFirstLevel" type="queryFirstLevel" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="statusQueryData" type="queryStatus" minOccurs="0"/>
          <xs:element name="timeSpanQueryData" type="queryTimespan" minOccurs="0"/>
					<xs:element name="sealQueryData" type="querySeal" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="queryFirstLevel">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="querySecondLevels" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="querySecondLevel" type="queryPart" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="queryPart">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="chosenAttributeStringId" type="xs:string" minOccurs="0"/>
          <xs:element name="chosenOperationId" type="xs:int" minOccurs="0"/>
          <xs:element name="dateATSelected" type="xs:boolean" minOccurs="0"/>
          <xs:element name="existingCriteria" type="xs:string" minOccurs="0"/>
          <xs:element name="freeTextCriteria" type="xs:string" minOccurs="0"/>
          <xs:element name="freeTextCriteriaSelected" type="xs:boolean" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="queryStatus">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="values" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="value" type="booleanKeyValueXML" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="typeOfStatus" type="typeOfStatusXML" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

	<xs:complexType name="timeseriesQuery">
		<xs:complexContent>
			<xs:extension base="abstractXMLElement">
				<xs:sequence>
					<xs:element name="qPart" type="queryPart" minOccurs="1" maxOccurs="1" />
					<xs:element name="quantor" type="timeseriesQuantor" minOccurs="1" maxOccurs="1" />
					<xs:element name="timespan" type="queryTimespan" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="querySeal">
		<xs:complexContent>
			<xs:extension base="abstractXMLElement">
				<xs:sequence>
					<xs:element name="values" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="value" type="booleanKeyValueXML"
									minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

  <xs:complexType name="booleanKeyValueXML">
    <xs:sequence/>
    <xs:attribute name="key" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>

  <xs:complexType name="queryTimespan">
    <xs:complexContent>
      <xs:extension base="abstractXMLElement">
        <xs:sequence>
          <xs:element name="endDate" type="xs:long"/>
          <xs:element name="endTimeFunction" type="timeFunctionXML"/>
          <xs:element name="startDate" type="xs:long"/>
          <xs:element name="startTimeFunction" type="timeFunctionXML"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="landscapeDiagramContentTypeXML">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INFORMATIONSYSTEMRELEASE"/>
      <xs:enumeration value="TECHNICALCOMPONENTRELEASE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="contentOption">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BUILDING_BLOCK"/>
      <xs:enumeration value="ATTRIBUTE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeOfStatusXML">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INFORMATIONSYSTEMRELEASE"/>
      <xs:enumeration value="TECHNICALCOMPONENTRELEASE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="timeFunctionXML">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ABSOLUTE"/>
      <xs:enumeration value="NOW"/>
      <xs:enumeration value="RELATIVE_PAST"/>
      <xs:enumeration value="RELATIVE_FUTURE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typeXML">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TECHNICALCOMPONENTRELEASE"/>
      <xs:enumeration value="INFORMATIONSYSTEMINTERFACE"/>
      <xs:enumeration value="INFORMATIONSYSTEMRELEASE"/>
      <xs:enumeration value="INFRASTRUCTUREELEMENT"/>
      <xs:enumeration value="PROJECT"/>
      <xs:enumeration value="BUSINESSUNIT"/>
      <xs:enumeration value="PRODUCT"/>
      <xs:enumeration value="BUSINESSPROCESS"/>
      <xs:enumeration value="BUSINESSOBJECT"/>
      <xs:enumeration value="ARCHITECTURALDOMAIN"/>
      <xs:enumeration value="INFORMATIONSYSTEMDOMAIN"/>
      <xs:enumeration value="BUSINESSFUNCTION"/>
      <xs:enumeration value="BUSINESSDOMAIN"/>
      <xs:enumeration value="BUSINESSMAPPING"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="sortMethodXML">
    <xs:restriction base="xs:string">
      <xs:enumeration value="HIERARCHICAL"/>
      <xs:enumeration value="NON_HIERARCHICAL"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="timeseriesQuantor">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="ALL" />
  		<xs:enumeration value="EXISTS" />
  	</xs:restriction>
  </xs:simpleType>
</xs:schema>

=== seventer/iteraplan/src/java/test/landscapeQueryTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<landscapeDiagramXML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" dialogStep="4" contentType="INFORMATIONSYSTEMRELEASE"
  xsi:schemaLocation="http://iteratec.iteraplan.com/ http://iteratec.iteraplan.com//LandscapeDiagramXML.xsd">
  <color attributeId="1">
    <attributeValues>
      <value>Gut</value>
      <value>Mittel</value>
      <value>Schlecht</value>
    </attributeValues>
    <selectedStyles>
      <style>AFCEA8</style>
      <style>F6DF95</style>
      <style>D79DAD</style>
    </selectedStyles>
  </color>
  <columnAxisScalesWithContent>false</columnAxisScalesWithContent>
  <columnQuery>
    <queryForms>
      <queryForm typeXML="BUSINESSPROCESS">
        <queryUserInput>
          <noAssignements>false</noAssignements>
          <queryFirstLevels>
            <queryFirstLevel>
              <querySecondLevels>
                <querySecondLevel>
                  <chosenAttributeStringId>blank_null_-1</chosenAttributeStringId>
                  <dateATSelected>false</dateATSelected>
                  <freeTextCriteriaSelected>true</freeTextCriteriaSelected>
                </querySecondLevel>
              </querySecondLevels>
            </queryFirstLevel>
          </queryFirstLevels>
        </queryUserInput>
      </queryForm>
    </queryForms>
  </columnQuery>
  <contentQuery>
    <queryForms>
      <queryForm typeXML="INFORMATIONSYSTEMRELEASE">
        <queryUserInput>
          <noAssignements>false</noAssignements>
          <queryFirstLevels>
            <queryFirstLevel>
              <querySecondLevels>
                <querySecondLevel>
                  <chosenAttributeStringId>userdefEnum_null_2</chosenAttributeStringId>
                  <chosenOperationId>2</chosenOperationId>
                  <dateATSelected>false</dateATSelected>
                  <freeTextCriteriaSelected>true</freeTextCriteriaSelected>
                </querySecondLevel>
              </querySecondLevels>
            </queryFirstLevel>
          </queryFirstLevels>
          <statusQueryData typeOfStatus="INFORMATIONSYSTEMRELEASE">
            <values>
              <value value="true" key="typeOfStatus_current" />
              <value value="false" key="typeOfStatus_planned" />
              <value value="false" key="typeOfStatus_target" />
              <value value="false" key="typeOfStatus_inactive" />
            </values>
          </statusQueryData>
          <timeSpanQueryData>
            <endDate>500000000</endDate>
            <endTimeFunction>RELATIVE_FUTURE</endTimeFunction>
            <startDate>-1</startDate>
            <startTimeFunction>NOW</startTimeFunction>
          </timeSpanQueryData>
        </queryUserInput>
      </queryForm>
    </queryForms>
    <selectedResultIds>
      <id>12</id>
    </selectedResultIds>
  </contentQuery>
  <lineType attributeId="2">
    <attributeValues>
      <value>Hoch</value>
      <value>Mittel</value>
      <value>Gering</value>
    </attributeValues>
    <selectedStyles>
      <style>1</style>
      <style>2</style>
      <style>3</style>
    </selectedStyles>
  </lineType>
  <rowQuery>
    <queryForms>
      <queryForm typeXML="BUSINESSUNIT">
        <queryUserInput>
          <noAssignements>false</noAssignements>
          <queryFirstLevels>
            <queryFirstLevel>
              <querySecondLevels>
                <querySecondLevel>
                  <chosenAttributeStringId>userdefEnum_null_4</chosenAttributeStringId>
                  <chosenOperationId>7</chosenOperationId>
                  <dateATSelected>false</dateATSelected>
                  <freeTextCriteriaSelected>true</freeTextCriteriaSelected>
                </querySecondLevel>
              </querySecondLevels>
            </queryFirstLevel>
          </queryFirstLevels>
        </queryUserInput>
      </queryForm>
    </queryForms>
    <selectedResultIds>
      <id>15</id>
    </selectedResultIds>
  </rowQuery>
  <selectedColumnAttributeId>-1</selectedColumnAttributeId>
  <selectedColumnOption>BUILDING_BLOCK</selectedColumnOption>
  <selectedColumnRelation>isrE16_businessProcess</selectedColumnRelation>
  <selectedRowAttributeId>-1</selectedRowAttributeId>
  <selectedRowOption>BUILDING_BLOCK</selectedRowOption>
  <selectedRowRelation>isrE16_businessUnit</selectedRowRelation>
  <sideAxisBottomLevel>2</sideAxisBottomLevel>
  <sideAxisTopLevel>1</sideAxisTopLevel>
  <topAxisBottomLevel>3</topAxisBottomLevel>
  <topAxisTopLevel>1</topAxisTopLevel>
  <version>@build.version@</version>
</landscapeDiagramXML>

=== seventer/iteraplan/src/resources/queries/landscapeQueryOne.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<landscapeDiagramXML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" dialogStep="2" contentType="INFORMATIONSYSTEMRELEASE"
  xsi:schemaLocation="http://iteratec.iteraplan.com/ http://iteratec.iteraplan.com//LandscapeDiagramXML.xsd">
  <color attributeId="@gesundheitszustand.id@">
    <attributeValues>
      <value>@gut@</value>
      <value>@mittel@</value>
      <value>@schlecht@</value>
    </attributeValues>
    <selectedStyles>
      <style>AFCEA8</style>
      <style>F6DF95</style>
      <style>D79DAD</style>
    </selectedStyles>
  </color>
  <columnAxisScalesWithContent>false</columnAxisScalesWithContent>
  <columnQuery>
    <queryForms>
      <queryForm typeXML="BUSINESSPROCESS">
        <queryUserInput>
          <noAssignements>false</noAssignements>
          <queryFirstLevels>
            <queryFirstLevel>
              <querySecondLevels>
                <querySecondLevel>
                  <chosenAttributeStringId>blank_null_-1</chosenAttributeStringId>
                  <dateATSelected>false</dateATSelected>
                  <freeTextCriteriaSelected>true</freeTextCriteriaSelected>
                </querySecondLevel>
              </querySecondLevels>
            </queryFirstLevel>
          </queryFirstLevels>
        </queryUserInput>
      </queryForm>
    </queryForms>
  </columnQuery>
  <contentQuery>
    <queryForms>
      <queryForm typeXML="INFORMATIONSYSTEMRELEASE">
        <queryUserInput>
          <noAssignements>false</noAssignements>
          <queryFirstLevels>
            <queryFirstLevel>
              <querySecondLevels>
                <querySecondLevel>
                  <chosenAttributeStringId>blank_null_-1</chosenAttributeStringId>
                  <dateATSelected>false</dateATSelected>
                  <freeTextCriteriaSelected>true</freeTextCriteriaSelected>
                </querySecondLevel>
              </querySecondLevels>
            </queryFirstLevel>
          </queryFirstLevels>
          <statusQueryData typeOfStatus="INFORMATIONSYSTEMRELEASE">
            <values>
              <value value="true" key="typeOfStatus_current" />
              <value value="true" key="typeOfStatus_planned" />
              <value value="true" key="typeOfStatus_target" />
              <value value="false" key="typeOfStatus_inactive" />
            </values>
          </statusQueryData>
          <timeSpanQueryData>
            <endDate>-1</endDate>
            <endTimeFunction>ABSOLUTE</endTimeFunction>
            <startDate>-1</startDate>
            <startTimeFunction>ABSOLUTE</startTimeFunction>
          </timeSpanQueryData>
        </queryUserInput>
      </queryForm>
    </queryForms>
  </contentQuery>
  <lineType attributeId="@komplexitt.id@">
    <attributeValues>
      <value>@hoch@</value>
      <value>@mittel@</value>
      <value>@gering@</value>
    </attributeValues>
    <selectedStyles>
      <style>1</style>
      <style>2</style>
      <style>3</style>
    </selectedStyles>
  </lineType>
  <rowQuery>
    <queryForms>
      <queryForm typeXML="BUSINESSUNIT">
        <queryUserInput>
          <noAssignements>false</noAssignements>
          <queryFirstLevels>
            <queryFirstLevel>
              <querySecondLevels>
                <querySecondLevel>
                  <chosenAttributeStringId>blank_null_-1</chosenAttributeStringId>
                  <dateATSelected>false</dateATSelected>
                  <freeTextCriteriaSelected>true</freeTextCriteriaSelected>
                </querySecondLevel>
              </querySecondLevels>
            </queryFirstLevel>
          </queryFirstLevels>
        </queryUserInput>
      </queryForm>
    </queryForms>
  </rowQuery>
  <selectedColumnAttributeId>-1</selectedColumnAttributeId>
  <selectedColumnOption>BUILDING_BLOCK</selectedColumnOption>
  <selectedColumnRelation>isrE16_businessProcess</selectedColumnRelation>
  <selectedRowAttributeId>-1</selectedRowAttributeId>
  <selectedGraphicsFormat>reports_export_SVG</selectedGraphicsFormat>
  <selectedRowOption>BUILDING_BLOCK</selectedRowOption>
  <selectedRowRelation>isrE16_businessUnit</selectedRowRelation>
  <sideAxisBottomLevel>2</sideAxisBottomLevel>
  <sideAxisTopLevel>1</sideAxisTopLevel>
  <topAxisBottomLevel>3</topAxisBottomLevel>
  <topAxisTopLevel>1</topAxisTopLevel>
  <version>@build.version@</version>
</landscapeDiagramXML>
